### ISSUE TITLE
Created Icons sometimes receive undesired dark fill

### ISSUE THREAD

**Issue by tannerbaum** [kodingdotninja/chakra-icons#392]
I've noticed this a couple of times now running the script, and looking into why and building a reproduction I noticed that the generated Icon loses the parent `fill:none` property if set. 

I'm no expert on SVGs so maybe our svgs shouldn't depend on top level properties, or that this is a by product of the SVGs I am grabbing from Figma. 

https://codesandbox.io/p/sandbox/xg4vp2

![Screenshot 2023-06-21 at 13 07 12](https://github.com/kodingdotninja/chakra-icons/assets/1280597/c2d3d7ce-2c7c-471a-953a-ff08f5ecf956)
![Screenshot 2023-06-21 at 13 07 47](https://github.com/kodingdotninja/chakra-icons/assets/1280597/a2d0d29d-223b-4fa3-9db2-f06d070ca932)

**Comment by r17x** [comment]
Hello @tannerbaum 

Thanks for make this issue, Will be fix in the next release. 


Thanks
