### ISSUE TITLE
Offload search API route

### ISSUE THREAD

**Issue by grikomsn** [kodingdotninja/chakra-icons#70]
Since we've moved to Cloudflare Pages, no need to work on this and wait for #429.

~~Current search API for the websites uses Next.js API routes, **which cannot be used if deploy statically on Render static websites**. Koding Ninja has Cloudflare Workers account ready. Offloading it there or even better, not using any external APIs would be great.~~

**Comment by ri7nz** [comment]
What it's `Offloading` ? Are you have any reference for me ? @grikomsn

**Comment by grikomsn** [comment]
In simple terms:

- if possible, move search API route to Cloudflare Workers, or
- rework search API without using Next.js API routes

**Comment by ri7nz** [comment]
@grikomsn  do you have any reference for `Cloudflare Workers` ?
